### ISSUE TITLE
数据能提供一下吗

### ISSUE THREAD

**Issue by scott-mao** [gggch414/LLKD#2]
你好，能提供一下咱们训练的数据集吗？谢谢

**Comment by gggch414** [comment]
Hi,
We've recently been finalizing our dataset. 
We will release our dataset as soon as possible.
Thank you for waiting.

**Comment by gggch414** [comment]
Hi, we added our dataset link.
Please check the README.md.
Thank you.

**Comment by qsqjava** [comment]
> 
您好，请问你这个代码跑通了吗？
