### ISSUE TITLE
Hello, I want to ask why an error is reported when running train: attributeerror: module'myloss'has no attribute'l_ feat_ ext'

### ISSUE THREAD

**Issue by qsqjava** [gggch414/LLKD#5]
Hello, I want to ask why an error is reported when running train: attributeerror: module'myloss'has no attribute'l_ feat_ ext'，and Is there any missing code in myloss file。

**Comment by gggch414** [comment]
Thank you for your feedback.
We have added 'L_feat_ext' in 'MyLoss'
