### ISSUE TITLE
I'm glad to hear from you, but here comes a new problem

### ISSUE THREAD

**Issue by qsqjava** [gggch414/LLKD#6]
I'm glad to hear from you, but here comes a new problem: attributeerror: module'myloss'has no attribute'l_ Mse', I look forward to your reply

**Comment by SeonggwanKo** [comment]
We have fixed the error.
Thank you for your patience.

**Comment by qsqjava** [comment]
> 我们已经修复了错误。 感谢您的耐心等待。

Thank you very much for your reply
